export const NEGATIVE_TEXT =
  "(normal aesthetic,bad aesthetic,worst quality,low quality,medium quality,illustration,3d,2d,painting,cartoons,sketch:1.4),(blurry:1.4),(depth of field,bokeh,blurred foreground),ugly,bad anatomy,poorly drawn face,poorly drawn hands,deformed,mutation,mutated hands,malformed limbs,extra fingers,extra arms,extra legs,extra limbs,missing fingers,fused fingers,missing arms,missing legs,bad proportions,extra digit,extra foot,bad body,bad feet,duplicate,long neck,tilted head,cross-eyed,looking away,facing away,gross proportions,fewer digits,morbid,mutilated,skin blemishes,skin spots,acnes,(fat:1.2),dehydrated,monochrome,grayscale,polar lowres,lowres,jpeg artifacts,cropped,teethcropped,text,error,signature,watermark,username,out of frame";

export const CONSTANT_TEXT_1 = "Natural Lighting, Studio lighting, Cinematic Lighting, Crepuscular Rays, X-Ray, Backlight";

export const CONSTANT_TEXT_2 =
  "insanely detailed and intricate, masterpiece, high_contrast, best quality, best aesthetic, stunning, Gorgeous, Surrealistic, Elegant, luxurious, subtle, delicate, captivating, in a symbolic and meaningful style, 8K";

export const TIPS_TEXT_1 =
  "Tips：Prompt 中的词语顺序代表其权重，越靠前权重越大。物体不要太多，两到三个就好。若要特别强调某个元素，可以加很多括号或者惊叹号，比如 beautiful forest background, desert!!, (((sunset))) 中会优先体现「desert」和「sunset」元素。";

export const TIPS_TEXT_2 =
  "假设你在提示词中使用了 mountain，生成的图像很可能会有树。但如果你想要生成没有树的山的图像，可以使用 mountain | tree:-10。其中 tree:-10 表示对于树的权重非常负，因此生成的图像中不会出现树。";

export const colorArray = [
  "white",
  "black",
  "darkgray",
  "gray",
  "lightslategray",
  "slategray",
  "darkslategray",
  "lightgray",
  "gainsboro",
  "whitesmoke",
  "snow",
  "ghostwhite",
  "floralwhite",
  "linen",
  "antiquewhite",
  "oldlace",
  "ivory",
  "seashell",
  "mintcream",
  "honeydew",
  "azure",
  "aliceblue",
  "lavender",
  "lightsteelblue",
  "slateblue",
  "mediumslateblue",
  "lightblue",
  "powderblue",
  "skyblue",
  "cornflowerblue",
  "royalblue",
  "mediumblue",
  "blue",
  "darkblue",
  "navy",
  "midnightblue",
  "teal",
  "darkcyan",
  "cadetblue",
  "mediumturquoise",
  "darkturquoise",
  "turquoise",
  "paleturquoise",
  "aquamarine",
  "lightcyan",
  "cyan",
  "dodgerblue",
  "darkgreen",
  "green",
  "forestgreen",
  "seagreen",
  "mediumseagreen",
  "mediumaquamarine",
  "darkseagreen",
  "lightseagreen",
  "springgreen",
  "mediumspringgreen",
  "lightgreen",
  "palegreen",
  "lime",
  "limegreen",
  "lawngreen",
  "chartreuse",
  "greenyellow",
  "yellowgreen",
  "darkolivegreen",
  "olivedrab",
  "olive",
  "darkkhaki",
  "khaki",
  "palegoldenrod",
  "lightyellow",
  "lightgoldenrodyellow",
  "lemonchiffon",
  "beige",
  "cornsilk",
  "wheat",
  "burlywood",
  "gold",
  "yellow",
  "darkorange",
  "orange",
  "sandybrown",
  "peachpuff",
  "papayawhip",
  "blanchedalmond",
  "bisque",
  "moccasin",
  "navajowhite",
  "peru",
  "darkgoldenrod",
  "goldenrod",
  "chocolate",
  "saddlebrown",
  "sienna",
  "rosybrown",
  "darksalmon",
  "salmon",
  "lightsalmon",
  "indianred",
  "firebrick",
  "brown",
  "maroon",
  "darkred",
  "red",
  "orangered",
  "tomato",
  "crimson",
  "coral",
  "lightpink",
  "pink",
  "hotpink",
  "deeppink",
  "palevioletred",
  "mediumvioletred",
  "lavenderblush",
  "lightcoral",
  "plum",
  "mediumorchid",
  "violet",
  "magenta",
  "fuchsia",
  "darkmagenta",
  "purple",
  "darkorchid",
  "darkviolet",
  "blueviolet",
  "mediumpurple",
  "indigo",
  "light_brown",
  "dark_pink",
  "blonde",
  "silver",
  "mistyrose",
  "steelblue",
  "thistle",
  "darkslateblue",
  "Iridescent",
  "Chromatic",
];
